### ISSUE TITLE
Gallery: weiße Linie unter Lupensymbol 

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#112]

**Comment by campusmedius** [comment]
.ngx-gallery-thumbnail .cm-square-zoom {
    top: 0;
    right: 1px;
    position: absolute;
    font-size: 1.1em;
    color: #b18691;
    background-color: #fff;
}

.cm-square-zoom:before {
    display: inline-block;
    width: 18px;
    left: -2px;
    position: relative;
}
