### ISSUE TITLE
Header inkl. Menu

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#13]
- Header-Menu sollte unterhalb des Headers aufklappen und sich auch wieder zusammenklappen lassen
- Header sollte wie timeline nur bis zum Sidepanel laufen
- Topography/Topology/Mediality gehören in meinen Augen ins Menu (nicht in den Header)
- Ich denke, wir brauchen auch ein Suchfeld, entweder separat im Header oder als Teil des Menu

**Comment by simgan** [comment]
MENU CM 2.0
- About
- Topography
- Topology
- Mediality
- Team
- Contact

**Comment by campusmedius** [comment]
Sidepanel wird nicht über den Header gezogen.
Suche wird vorerst nicht implementiert.
Header-Menu Farbe wie Timeline.

**Comment by simgan** [comment]
Neue Header-Gestaltung laut Gespräch vom 14.11.2018:
links Bar-Menu, Mitte Logo, rechts EN/DE
