### ISSUE TITLE
Mobile (iphone): Schriftprobleme in horizontaler Haltung

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#132]
Wenn ich das iPhone nicht vertikal, sondern horizontal halte, kommen die Schriftgrößen durcheinander (siehe screenshot unten).
![image](https://user-images.githubusercontent.com/7826143/51831335-22a24280-22f2-11e9-80d4-16ffae833112.png)

**Comment by campusmedius** [comment]
https://stackoverflow.com/questions/2710764/preserve-html-font-size-when-iphone-orientation-changes-from-portrait-to-landsca
