### ISSUE TITLE
Favicon für die Website

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#14]

**Comment by simgan** [comment]
Titel der Website ist Campus Medius, nicht Campusmedius

**Comment by iamsusey** [comment]
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/favicon + logo/campusmedius-favicon.ico

hochauflösend auch für Retina

**Comment by simgan** [comment]
Hab Verrlauf gelöscht und Seite neu geladen: Sehe kein neues Favicon.

**Comment by simgan** [comment]
Sorry, muss nochmals besprochen werden: Favicon ist undeutlich, ev. fetter setzen oder mit mehr space
