### ISSUE TITLE
Desktop: +/- ist auf map nicht zu sehen

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#140]
Bug auf allen desktop-Plattformen, in PC/Chrome außerdem weißer Rand am unteren Ran der map

**Comment by simgan** [comment]
![map-issue](https://user-images.githubusercontent.com/7826143/51898808-06fe7100-23b2-11e9-8d54-84daf05807d1.png)

**Comment by campusmedius** [comment]
+ nowebgl message
