### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#15]
- ~~Farbton stimmt nicht mit Entwurf überein~~
- Auflösung zu klein
- ~~bei +/– ist – zu klein (muss gleich breit sein wie +)~~
- ~~blaues Quadrat erscheint bei ausgewähltem pin~~
- ~~Pfade fehlen noch~~
- ~~ausgewählter event sollte auch bei full info auf map sichtbar bleiben~~
- ~~zoom click center~~
- Max. (15) und min. zoom festlegen
- ~~1933er Karte ein- und ausblenden? Ja.~~
- ~~OSM designen (analog zu Topology)? Nein.~~

**Comment by simgan** [comment]
Wie Pfade gestalten?

**Comment by iamsusey** [comment]
Datei für Karte
/Users/Susi/Dropbox/Campus Medius Visuals/Update 2017/Design/Final/Update 12-2018/Stadtplan_Wien_1933_pink.png

Layers-Icon für Ein- und Ausblenden der historischen Karte

**Comment by simgan** [comment]
Pfade:
- Pfade stimmen nicht genau (siehe etwa Wagramer Straße), müssen exakt dem Straßenverlauf folgen
- Frage der Farbdarstellung: Verwechslungsgefahr mit bereits vorhandenen dunkelgrauen Linien
