### ISSUE TITLE
Information Sidepanel

### ISSUE THREAD

**Issue by campusmedius** [campusmedius/campusmedius#2]
3 breiten implementiern:
- ~40% bei Einstieg, kein Event ausgewählt
- ~20% Event ausgewählt, kurz Info
- ~70% Event ausgewählt, full Info

Bug: Sidepanel verschwindet bei ESC

**Comment by simgan** [comment]
Wir sollten überlegen, die Breite des Sidepanels für Full-Info an die Textmenge anzupassen. In der Topography, wo die Texte generell kürzer sind als in der Topology, würden ca. 50 % ausreichen.

**Comment by simgan** [comment]
Ich würde folgende Einstellungen vorschlagen:
- Short-Info 25%
- Topography 50%
- Topology 75%

**Comment by simgan** [comment]
Warum wurde diese Issue geschlossen? Sehe keine Veränderung.

**Comment by simgan** [comment]
Sorry, muss ich nochmals aufmachen: bin eher für Verh. 25/50/75
