### ISSUE TITLE
Typo-Überarbeitungen

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#24]
- Größenverhältnisse und Zeilenabstände auf ganzer Seite kontrollieren und ggf. korrigieren (Orientierung an Fließtext: Source Serif Pro 20px)
- Hyperlinks immer in roter Farbe? Oder besser nur unterstrichen? (siehe dazu auch #29 )
- Je nach Bildschirm erscheint Farbton eher als rosarot => ev. dunkler machen
- Für Fließtext Grauton für ideale Lesbarkeit finden (d.h. nicht zu hell und nicht zu dunkel)
- Bei Zwischentitel mehr Abstand nach oben (und ev. auch nach unten)
- Blockquotes in Serifen und größer
- Listendarstellung stylen?
- Logo: ev. campus sans und medius serif

**Comment by iamsusey** [comment]
> * Größenverhältnisse und Zeilenabstände auf ganzer Seite kontrollieren und ggf. korrigieren (Orientierung an Fließtext: Source Serif Pro 20px)
für Desktop passen alle Größen so.

> * Hyperlinks immer in roter Farbe? Oder besser nur unterstrichen? (siehe dazu auch #29 )
rosa + unterstrichen

> * Je nach Bildschirm erscheint Farbton eher als rosarot => ev. dunkler machen
neuer Farbton: #b18691
siehe 
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/Update 12-2018/campus-medius-redesign-v7-03.png

> * Bei Zwischentitel mehr Abstand nach oben (und ev. auch nach unten)
nach oben das 4-fache wie unten
siehe
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/Update 12-2018/campus-medius-redesign-v7-04.png

> * Logo: ev. campus sans und medius serif
siehe 
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/favicon + logo/campusmedius-logo.svg


> * Für Fließtext Grauton für ideale Lesbarkeit finden (d.h. nicht zu hell und nicht zu dunkel)
> * Blockquotes in Serifen und größer
> * Listendarstellung stylen?

**Comment by iamsusey** [comment]
**Blockquotes:**
Source Serif Pro
könnte finde ich gleich groß wie Fließtext sein, da ja schon farblich abgesetzt. Oder was denkt ihr?
Sonst gleich groß wie neue Captions (das war glaub ich font-size: 0.9rem und line-height: 1.5)

**Listendarstellung:**
_List-Item (<li>) :_ margin-bottom: 1em
_Listen (<ul>, <ol>) :_ zusätzlich 1em nach unten, also insgesamt doppelt so viel wie zwischen den List-items

**ad Spaltenbreite:**
ja, ich fände es besser wenn wir dem Text eine maximal-Breite geben könnten:
max-width: 1400px

**line-height Titel**
ja, der ist jetzt nur 1-fach, der darf gerne 1.2-fach werden (in dem Fall line-height: 36px bei font-size:30px)

**Comment by simgan** [comment]
Ad Blockquotes: Ja, Source Serif Pro 20px, und dunkelgrauer, weil sonst schlecht lesbar.
