### ISSUE TITLE
Link-Typen gestalten

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#29]
Wir müssen nochmals überlegen, wie wir die unterschiedlichen Link-Typen gestalten sollen:
- externe Links auf andere Websites (unterstrichen und Pfeil)
- interne Links auf andere Pages (unterstrichen)
- interne Links innerhalb einer Page (ev. analog zu Notes umsetzen, aber statt + mit ↓ bzw. ↑)

Punkt 3 ist noch offen, müssen wir besprechen.

**Comment by campusmedius** [comment]
Für die Codierung in HTML:
<a cmLinkExtern href="url">Link Text</a>
<a cmLinkIntern href="url">Link Text</a>
<a cmLinkInPage href="#anchor">Link Text</a>

**Comment by iamsusey** [comment]
Links immer rosa unterstrichen

external-link Icon hinzugefügt,
siehe auch
/Users/Susi/Dropbox/Campus Medius Visuals/Update 2017/Design/Final/Update 12-2018/campus-medius-redesign-v7-05-external-link.png

**Comment by campusmedius** [comment]
Für das external link icon bitte noch folgendes ändern:
- Icon Größe gleich lassen
- Größe des Symbol im Icon verkleinern
- Baseline des Symbols im Icon gleich lassen
