### ISSUE TITLE
Event-Issues

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#30]
- Kursivierung sollte auch im Event-Titel möglich sein
- Eingabe der Short-Info fehlt noch
- URL der Events sollte Event-Titel enthalten
- Dargestellte Zeitdauer stimmt nicht mit Eingabe überein (+1h)

**Comment by campusmedius** [comment]
- Kursivierung sollte auch im Event-Titel möglich sein <- nicht umsetzbar
- URL der Events sollte Event-Titel enthalten <- zu Zitierung verschoben
