### ISSUE TITLE
Personen in captions zur GND verlinken

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#32]
Um in den media captions keine biografischen Daten angeben zu müssen, sollen die Personennamen zur GND verlinkt werden. Das wird nach meinen Infos aber nicht als normaler Link gemacht, sondern via BEACON: https://de.wikipedia.org/wiki/Wikipedia:BEACON

**Comment by campusmedius** [comment]
Verstehe ich nicht. Gibts da ein Beispiel für eine Url.
Ich würde einfach einen externen Link zur Personeninfo setzen.

**Comment by campusmedius** [comment]
Antwort Ingo:
Beacon-Files sind txt-files, in denen die GND-Nummern zu einer Ressource aufgelistet werden, pro Zeile eine GND-Nummer, dann ein Trennzeichen (wobei ich grad nich weiß, welches..) und der Link, unter dem Informationen zur Person in eurer Ressource gefunden werden können. Mich wundert’s eigentlich nicht, dass es ein Programmierer nicht kennt. Dürfte ein deutsche Sonderlösung sein (getragen von der GND). Die Überzeugende Suchanwendung für die Files, für die man das ja bauen würde, kenn’ ich nicht. Google würd’ sich wohl eher über RDFa (https://de.wikipedia.org/wiki/RDFa) freuen und wenn die Daten wirklich nachhaltig weitergenutzt werden sollen, hilft wahrscheinlich eine dokumentierte API mehr als diese Files.

**Comment by campusmedius** [comment]
Da GND kein Linkformat ist sehe ich nicht wie wir das verwenden können.
Würde einfach Links zu einer externen Personenbeschreibung setzen.
