### ISSUE TITLE
Https Zertifikat

### ISSUE THREAD

**Issue by campusmedius** [campusmedius/campusmedius#33]

**Comment by campusmedius** [comment]
Im Moment nur http. Wenn wir die Domain umgestellt haben können wir ein https Zertifikat ausstellen.

**Comment by simgan** [comment]
Das müssen wir besprechen, ich informiere mich nämlich gerade, ob wir die Domain bei Yahoo verlängern oder z.B. zu GoDaddy wechseln sollen. Laut Maurice: "als reiner registrar ist GoDaddy ok, für zertifikate (ssl bzw. https) und anderes gibt es bessere / billigere lösungen".
