### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by campusmedius** [campusmedius/campusmedius#4]
Für die Topography brauchen wir folgende Icons:
- Bars menu links oben
- Event navigation <, |, >
- Gallery <, >, x, lupe
- external link
- quote
- intext icons: footnote, bild, video, audio, +, x

Die Icons sollen als Font erstellt werden. Bitte dazu folgendes online Tool verwenden:
https://icomoon.io/app/#/select

Bei icomoon kann man alle icons als SVG hochladen und es wird dafür eine Font generiert.
Bitte daruaf achten, dass die SVG nur eine Farbe haben.

**Comment by simgan** [comment]
Audio-Icon ist schlecht erkennbar, muss ev. ersetzt werden.

**Comment by iamsusey** [comment]
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/cm-icons

- neues Audio-Icon (Lautsprecher)
- intext icons jeweils mit square und ohne
- topology icons (mit circle und ohne)
- quote (mit square und ohne)
- layers-icon für Karte (mit square und ohne)
- menu
- seperator |
-  chevrons (< > usw.) in normal + bold + double

**Comment by iamsusey** [comment]
siehe:
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/cm-icons
