### ISSUE TITLE
Note + Italics => kein Abstand

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#44]
Wenn der Satz nach einer Note mit einem kursiven Wort beginnt, fehlt der Abstand, siehe etwa https://131.130.75.201/topography/events/23?lang=de&info=full (vor "_Turksib_ war bei…")

**Comment by campusmedius** [comment]
Das Leerzeichen in den i Tag geben. Zum Beispiel:
`</cm-note><i>` Turksib</i>`
