### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#58]
- external link icon verkleinern (und zwischen icon und text nur einen normalgroßen Abstand)
- image icon ist schlecht erkennbar
- link-icon zu schlecht erkennbar (siehe #62)
- scroll-up icon für mobile
- loading icon (wenn page lädt, jetzt: "Loading…")
- Wir verwenden für das ausgewählte Ereignis in der timeline jetzt die rosarote Farbe. Da haben wir diskutiert, ob wir das Rosarot nicht auch sonst einsetzen könnten, z.B. im Logo/Favicon. (Ist nur eine Anregung/Frage, muss nicht sein.)

**Comment by iamsusey** [comment]
Update in der Dropbox mit
_ geändertes external link icon (kleiner)
_ alternative Version des image-icons (größer)
_ share icon
_ back-to-top icon

Dropbox/Campus Medius Visuals/Update 2017/Design/Final/cm-icons

**Comment by iamsusey** [comment]
Loading Icon:

es liegen zwei Icons in der Dropbox:
Dropbox/Campus Medius Visuals/Update 2017/Design/Final/Update 12-2018/icon loading

entweder als animiertes GIF einbinden, oder das SVG rotieren
