### ISSUE TITLE
Medienobjekte downloaden deaktivieren

### ISSUE THREAD

**Issue by simgan** [campusmedius/campusmedius#66]
Nun wieder möglich, Medienobjekte herunterzuladen bzw. in neuen Tab zu öffnen (unterschiedlich je nach Browser). Bitte bei allen Objekten (image, video, audio) deaktivieren.

**Comment by campusmedius** [comment]
Bitte beschreiben wo es konkret Probleme gibt. Bei mir unter Chrome sind downloads deaktiviert.

**Comment by simgan** [comment]
Problem (d.h. Möglichkeit, Medienobjekt herunterzuladen oder separat zu öffnen) tritt nur mehr bei Audio auf (Mac: Chrome, Safari, Firefox; PC: Firefox, IE?)
